openapi: 3.0.0
info:
  title: Relatom backend api
  version: '1.0'
  license:
    name: AGPL 3.0
servers:
  - url: 'http://api.ckcfeins.relatom.test'
    description: Test server
paths:
  /events:
    get:
      summary: Get all the events
      tags: []
      responses:
        '200':
          description: OK
          headers: {}
      operationId: get-events
      parameters: []
      description: Get all the events
    post:
      summary: Store an event
      tags: []
      responses: {}
      operationId: store-event
      description: Create a new event
      parameters: []
  '/events/{event}':
    parameters:
      - schema:
          type: string
        name: event
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-events-event
      description: Get event
      parameters: []
components:
  schemas: {}
  securitySchemes: {}
